# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OiwOsLOC1UJFTL17-V8EYnKr9twqjbOU
"""

# import socket module
import socket

# get hostname
hostname=input("Input hostname: ")

# get ip of hostname
ip=socket.gethostbyname(hostname)
print(ip)