# -*- coding: utf-8 -*-
"""pong_server.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15jjwDBQgdC5aZGtFNswbwVHBF5htvVNa
"""

import socket

def initiatePongServer():
  s=socket.socket() #create socket
  print("Socket succcesfully created")

  #Server port
  port = 7000
  s.bind(('',port))

  #Start listening to requests
  s.listen(5)
  print("Socket is listening....")

  # Pong server running forever
  while True:
    #Establish connection with client
    connection, address=s.accept()
    print('Socket connected to ', address)
    message =connection.recv(1024)
    print(message)
    # Respond the client with Pong
    connection.send(str('Pong').encode())

    #Close connection with client
    connection.close()

# driver function
if __name__ == '__main__':

  #Trigger Pong server
  initiatePongServer()
